language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
before_install:
    - sudo add-apt-repository ppa:rethinkdb/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install rethinkdb -y
before_script:
    - rethinkdb --daemon
